# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: 'jdk+fx'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn package test allure:report -Pbuild -fjava/pom.xml
      - name: webdriver-server startup
        run: docker-compose -f test/docker-compose.yml up -d
      - name: chrome-test
        run: java -cp ./java/target/sebuilder-interpreter-2.0.0-SNAPSHOT-jar-with-dependencies.jar com.sebuilder.interpreter.application.SeInterpreter --resultoutput=chrome --datasource.directory=test/suite/input --driver.remote-url=http://localhost:4444 --reportFormat=ExtentReports test/suite/testsuite.json
      - name: Upload chrome result
        uses: actions/upload-artifact@v3
        with:
          name: chrome-result
          path: chrome
