# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: 'jdk+fx'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn package test allure:report -Pbuild -fjava/pom.xml
      shell: cmd
    - name: Upload TestReport
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: ./java/target/site
    - name: jlink
      run: jlink --module-path "C:\hostedtoolcache\windows\Java_Zulu_jdk+fx\17.0.3-7\x64\jmods" --add-modules java.base,java.compiler,java.datatransfer,java.xml,java.prefs,java.desktop,java.logging,java.management,java.security.sasl,java.naming,java.rmi,java.scripting,java.security.jgss,java.transaction.xa,java.sql,jdk.unsupported,jdk.charsets,javafx.base,javafx.graphics,javafx.controls,javafx.fxml --compress=2 --output jre
      shell: cmd

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: 'site/allure-maven-plugin'